### ISSUE TITLE
赞一个，有 问题想请教。

### ISSUE THREAD

**Issue by huangguozhen** [aliyun-linkdevelop/airmonitor_demo#1]
首先看到作者开发是使用PlatformIO开发的，非常兴奋。

由于本人并非嵌入式出身，对设备端开发理解比较浅。最近几天就一直在思考能不能使用PlatformIO基于Ardiuno开发。

首先、看到作者连上阿里云是自己使用MQTT连接平台的，我想请教一下可不可使用官方插件`iotkit-embbeded`。

其次、我要开发的设备是`安信可 ESP-12F或IntoRobot-W6`，这个设备在PlatformIO上找不到相应的Board的，我应该选择哪个Board开发。
谢谢！

**Comment by ohdarling** [comment]
1. iotkit-embbeded 并不是 for Arduino 的哦
2. ESP-12F 就是 ESP8266，IntoRobot-W6 也是基于 ESP8266EX 芯片组，看了下规格应该是 ESP-12E 或者 ESP-12F
3. Board 可以选择使用 Espressif ESP8266 ESP-12E

**Comment by huangguozhen** [comment]
@ohdarling 谢谢，ESP-12E烧录设置的`flash_mode`是`dio`。IntoRobot-W6规格书上注明烧录用`qio`。这个在PlatformIO中哪里可以修改吗？

**Comment by ohdarling** [comment]
http://docs.platformio.org/en/latest/platforms/espressif8266.html
```
[env:myenv]
board_flash_mode = qio
```
在 `platformio.ini` 中添加一行指定模式

**Comment by huangguozhen** [comment]
@ohdarling 谢谢，我选择`nodemcu（esp 12 module）`这个板子开发。可以正常运行。
