### ISSUE TITLE
MQTT_MAX_PACKET_SIZE should be set to 1024 and MQTT_SOCKET_TIMEOUT should be set to > 30

### ISSUE THREAD

**Issue by NirViaje** [aliyun-linkdevelop/airmonitor_demo#3]
According to the document of MQTT-TCP:

> Variable header: Keep Alive | The Keep Alive parameter must be included in the CONNECT packet. The allowed range of Keep Alive value is 30-1200 seconds. If the value of Keep Alive is not in this range, IoT Platform will reject the connection. We recommend that you set a value larger than 300 seconds. If the Internet connection is not stable, set a larger value.
> -- | --
>
> https://partners-intl.aliyun.com/help/doc-detail/73742.htm
> https://www.alibabacloud.com/help/zh/doc-detail/73742.htm

依据MQTT-TCP官方文档，keepalive心跳包参数需设置到30秒以上，否则阿里云mqtt服务器拒接连接。建议设置为60~300秒之间。

**Comment by ohdarling** [comment]
在 PubSubClient.h 中已经把超时设置改到 60 秒了

https://github.com/aliyun-linkdevelop/airmonitor_demo/blob/d94188994ec97df709e0a1e90ee32952183fb8d7/airmonitor_device/lib/PubSubClient/src/PubSubClient.h#L31

这个代码应该是可以直接跑起来并且连接到阿里云 MQTT 服务器上。
